// <auto-generated />
namespace K22CNT4_TTCD1_NguyenThiTraMi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateReview));
        
        string IMigrationMetadata.Id
        {
            get { return "202410301537463_updateReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
